from .jsonParserNode import NODE_CLASS_MAPPINGS as JSON_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as JSON_NODE_DISPLAY_NAME_MAPPINGS
from .imageTransformNode import NODE_CLASS_MAPPINGS as IMAGE_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as IMAGE_NODE_DISPLAY_NAME_MAPPINGS

# Combine the node class mappings from both files
NODE_CLASS_MAPPINGS = {
    **JSON_NODE_CLASS_MAPPINGS,
    **IMAGE_NODE_CLASS_MAPPINGS
}

# Combine the display name mappings from both files
NODE_DISPLAY_NAME_MAPPINGS = {
    **JSON_NODE_DISPLAY_NAME_MAPPINGS,
    **IMAGE_NODE_DISPLAY_NAME_MAPPINGS
}
